apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql
  namespace: expense
  labels: 
    app: mysql
    tier: db
    project: expense 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: nginx 
        image: ramak8sgcp/mysql:v1
        readinessProbe:
          tcpSocket:
          port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1 
kind: Service 
metadata:
  name: mysql
  namespace: expense 
spec:
  selector:
    app: mysql
    tier: db
    project: expense 
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 80
      